# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Finance-Currency-Convert-DnB
version:      0.2
version_from: lib/Finance/Currency/Convert/DnB.pm
installdirs:  site
requires:
    File::Spec:                    0
    LWP::Simple:                   0
    Slurp:                         0
    Test::More:                    0
    XML::Simple:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
